Repository FuelRats/fuelrats.com, pull requests merged in 2018-05, with the labels that each got.

#73 Update LICENSE
  LICENSE
Labels: :gear: Task, :skull_and_crossbones: Urgent

#75 more fixes cuz I did it wrong the last time
  LICENSE
Labels: :bug: Bugfix

#76 rework paperwork submission logic to make more sense.
  pages/paperwork/edit.js
  store/actions/rescues.js
Labels: :bug: Bugfix

#80 v1.3.1
  components/RescuesByRatTable.js
  pages/_document.js
  server/config/router.js
  static/browserconfig.xml
  static/favicon/favicon-16.png
  static/favicon/favicon-196.png
  static/favicon/favicon-32.png
  static/favicon/favicon-512.png
  static/favicon/favicon-96.png
  static/manifest.json
  static/sitemap.xml
Labels: :package: Release, :zap: Enhancement

#81 Fix oauth flow error
  pages/authorize.js
  pages/password-reset.js
  pages/register.js
  store/actions/authentication.js
Labels: :bug: Bugfix, :skull_and_crossbones: Urgent
