Repository FuelRats/fuelrats.com, pull requests merged in 2019-11, with the labels that each got.

#188 Fix firefox autofill
  client/components/AppLayout.js
  client/components/LoginModal.js
  client/components/ValidatedFormInput.js
Labels: :bug: Bugfix

#189 [WEB-251] don't feed garbage data to system input if stored system is null
  client/pages/paperwork/edit.js
Labels: :bug: Bugfix

#190 [WEB-242] API Master Reducer
  client/components/AddNicknameForm.js
  client/components/AddRatForm.js
  client/components/AppLayout.js
  client/components/FirstLoginModal.js
  client/components/LoginModal.js
  client/components/ProfileHeader.js
  client/components/RatCard.js
  client/components/RatCard/DefaultRatButton.js
  client/components/UserMenu.js
  client/components/UserNicknamesPanel.js
  client/components/UserRatsPanel.js
  client/helpers/initUserSession.js
  client/pages/paperwork/edit.js
  client/pages/paperwork/view.js
  client/store/actions/partials.js
  client/store/actions/rats.js
  client/store/actions/rescues.js
  client/store/actions/services.js
  client/store/actions/user.js
  client/store/initialState.js
  client/store/reducers/APIResource.js
  client/store/reducers/authentication.js
  client/store/reducers/decals.js
  client/store/reducers/groups.js
  client/store/reducers/index.js
  client/store/reducers/orders.js
  client/store/reducers/rats.js
  client/store/reducers/rescues.js
  client/store/reducers/ships.js
  client/store/reducers/user.js
  client/store/reducers/users.js
  client/store/selectors/index.js
  client/store/selectors/user.js
  client/store/selectors/users.js
  client/store/utility/chainReducers.js
  client/store/utility/withDefaultReducers.js
Labels: :sparkles: Feature, :zap: Enhancement

#192 Update stuff, also ALSO fix some paperwork bugs n stuff \o/
  CONTRIBUTING.md
  client/components/AddRatForm.js
  client/components/Carousel.js
  client/components/Modal.js
  client/components/Modal/ModalContent.js
  client/components/Modal/ModalFooter.js
  client/components/Nav.js
  client/components/PageWrapper.js
  client/components/RadioCardInput.js
  client/components/RadioOptionsInput.js
  client/components/RatCard.js
  client/components/Switch.js
  client/components/TabbedPanel.js
  client/components/TagsInput.js
  client/components/TermsModal.js
  client/components/TextPlaceholder.js
  client/components/ValidatedFormInput.js
  client/helpers/parseJSONAPIResponseForEntityType.js
  client/pages/admin/rescues/list.js
  client/pages/paperwork/edit.js
  client/pages/paperwork/view.js
  client/pages/storefront/cart.js
  client/pages/storefront/checkout.js
  client/pages/storefront/orders.js
  client/store/actions/authentication.js
  client/store/actions/blogs.js
  client/store/actions/decals.js
  client/store/actions/epics.js
  client/store/actions/leaderboard.js
  client/store/actions/rats.js
  client/store/actions/rescues.js
  client/store/actions/services.js
  client/store/actions/ships.js
  client/store/actions/stripe.js
  client/store/actions/user.js
  client/store/index.js
  client/store/reducers/index.js
  client/store/selectors/blogs.js
  client/store/selectors/pageViews.js
  client/store/selectors/rats.js
  client/store/selectors/ships.js
  client/store/selectors/users.js
  package.json
  yarn.lock
Labels: :bug: Bugfix, :zap: Enhancement

#194 Feat/rework fl paperwork
  client/components/TagsInput.js
  client/pages/paperwork/edit.js
Labels: :sparkles: Feature

#195 [WEB-245] Replace next-routes with built-in dynamic routing
  client/components/AdminUserMenuNav.js
  client/components/AppLayout/PageTransitionContainer.js
  client/components/AppLayout/PageWrapper.js
  client/components/Header.js
  client/components/LoginModal.js
  client/components/Nav.js
  client/components/UserMenu.js
  client/pages/[slug].js
  client/pages/admin/rescues/index.js
  client/pages/blog/[blogId].js
  client/pages/blog/author/[author]/index.js
  client/pages/blog/author/[author]/page/[page].js
  client/pages/blog/category/[category]/index.js
  client/pages/blog/category/[category]/page/[page].js
  client/pages/blog/index.js
  client/pages/blog/page/[page].js
  client/pages/epic/nominate.js
  client/pages/index.js
  client/pages/paperwork/[rescueId]/edit.js
  client/pages/paperwork/[rescueId]/index.js
  client/pages/paperwork/[rescueId]/view.js
  client/pages/password-reset.js
  client/pages/profile/[tab].js
  client/pages/store/cart.js
  client/pages/store/checkout.js
  client/pages/store/orders.js
  client/pages/store/products/[page].js
  client/pages/store/products/index.js
  client/pages/version/index.js
  client/pages/version/raw.js
  client/routes.js
  client/scss/animations/_wiggle.scss
  client/scss/components/_page.scss
  client/scss/core/_svg.scss
  package.json
  server/middlewares/router.js
  yarn.lock
Labels: :sparkles: Feature, :zap: Enhancement

#196 Bout time we get a proper changelog file in here
  CHANGELOG.md
Labels: :gear: Task

#197 [WEB-225] Replace profile settings tab with password change modal
  CHANGELOG.md
  CONTRIBUTING.md
  client/components/AppLayout/AppLayout.js
  client/components/ChangePasswordModal.js
  client/components/FirstLoginModal.js
  client/components/PasswordField.js
  client/components/ProfileHeader.js
  client/components/UserSettings.js
  client/pages/profile/[tab].js
  client/scss/_root.scss
  client/scss/components/_input-group.scss
  client/scss/components/_password-group.scss
  client/scss/components/_profile-header.scss
  client/scss/components/_store-error.scss
  client/scss/core/_application.scss
  client/scss/core/_dialog.scss
  client/scss/core/_input.scss
Labels: :bug: Bugfix, :sparkles: Feature, :zap: Enhancement

#198 [WEB-222] Rewrite RadioOptionsInput
  .stylelintignore
  CHANGELOG.md
  client/components/RadioCardInput.js
  client/components/RadioInput/RadioInput.js
  client/components/RadioInput/RadioInputOption.js
  client/components/RadioInput/index.js
  client/components/RadioOptionsInput.js
  client/components/storefront/CheckoutForm.js
  client/pages/epic/nominate.js
  client/pages/paperwork/[rescueId]/edit.js
  client/pages/register.js
  client/pages/store/checkout.js
  client/scss/components/_radio-input.scss
Labels: :zap: Enhancement
