Repository FuelRats/fuelrats.com, pull requests merged in 2019-05, with the labels that each got.

#144 [WEB-82] Added CMDR name/title to edit paperwork
  client/pages/paperwork/edit.js
  client/scss/pages/_paperwork.scss
Labels: :zap: Enhancement

#145 Fix paperwork pages
  client/pages/paperwork/edit.js
  client/pages/paperwork/view.js
Labels: :bug: Bugfix

#146 Fix inactive cases showing active
  client/pages/paperwork/view.js
Labels: :bug: Bugfix

#149 Updated CONTRIBUTING doc with minor changes
  CONTRIBUTING.md
Labels: :gear: Task

#150 [WEB-193] Replaced flex with grid styling on products.
  client/components/storefront/ProductCard.js
  client/scss/components/_product-card.scss
Labels: :zap: Enhancement
