Repository FuelRats/fuelrats.com, pull requests merged in 2019-07, with the labels that each got.

#176 Teamcity CI configuration changes
  .eslintignore
  .gitignore
  .travis.yml
  client/components/Header.js
  client/pages/version.js
  client/scss/components/_profile-header.scss
  client/scss/components/_user-nicknames.scss
  client/scss/mixins/_text-outline.scss
  client/store/reducers/error.js
  deploy_rsa.enc
  deploy_rsa.pub
  next.config.js
  package.json
  scripts/deploy.sh
  yarn.lock
Labels: :gear: Task

#177 Upgrade to ESLint v6
  .eslintrc.js
  client/components/AppLayout.js
  client/components/storefront/StoreControlBar.js
  client/pages/admin/rescues/list.js
  client/pages/epics/nominate.js
  client/pages/register.js
  package.json
  server/middlewares/router.js
  yarn.lock
Labels: :gear: Task

#179 Fix/privacy link
  .all-contributorsrc
  CONTRIBUTORS.md
  client/pages/i-need-fuel.js
  client/pages/register.js
Labels: :bug: Bugfix

#182 fix(input-group-border): fix missing border
  client/scss/components/_input-group.scss
Labels: :bug: Bugfix

#183 Disable store
  client/pages/storefront/checkout.js
  client/pages/storefront/list.js
  client/scss/_helpers.scss
  client/scss/helpers/_disabled.scss
  client/scss/helpers/_text-format.scss
Labels: :skull_and_crossbones: Urgent
