Repository FuelRats/fuelrats.com, pull requests merged in 2019-12, with the labels that each got.

#200 Feat/web 218/user menu
  client/components/AdminUserMenuNav.js
  client/components/UserMenu.js
  client/scss/components/_user-menu.scss
Labels: :zap: Enhancement

#201 Fix actionTypes object
  CHANGELOG.md
  client/store/actionTypes.js
  client/store/actions/authentication.js
  client/store/index.js
Labels: :bug: Bugfix, :zap: Enhancement

#202 [WEB-137] [WEB-227] Add nickname reminder
  CHANGELOG.md
  client/components/AddNicknameForm.js
  client/components/InfoBubble.js
  client/components/ValidatedFormInput.js
  client/scss/_components.scss
  client/scss/components/_add-nickname-form.scss
  client/scss/components/_info-bubble.scss
  client/scss/components/_user-nicknames.scss
  client/scss/core/_input.scss
  client/scss/fonts/_open-sans.scss
  client/scss/fonts/_raleway.scss
Labels: :sparkles: Feature, :zap: Enhancement

#204 Feat/web 218/user menu
  client/components/UserMenu.js
  client/scss/components/_user-menu.scss
Labels: :zap: Enhancement

#206 Fix/null data paperwork
  CHANGELOG.md
  client/pages/paperwork/[rescueId]/index.js
Labels: :bug: Bugfix, :skull_and_crossbones: Urgent

#205 2.9 cleanup / update prep
  CHANGELOG.md
  client/components/AddNicknameForm.js
  client/components/AddRatForm.js
  client/components/AppLayout/AppLayout.js
  client/components/FirstLoginModal.js
  client/components/ProfileHeader.js
  client/components/RatCard/DefaultRatButton.js
  client/components/RatCard/RatCard.js
  client/components/UserMenu.js
  client/components/UserMenu/NavItem.js
  client/components/UserMenu/NavSection.js
  client/components/UserMenu/UserMenu.js
  client/components/UserMenu/index.js
  client/components/UserNicknamesPanel.js
  client/components/UserRatsPanel.js
  client/pages/paperwork/[rescueId]/edit.js
  client/pages/paperwork/[rescueId]/index.js
  client/pages/store/products/index.js
  client/pages/version/index.js
  client/scss/components/_user-menu.scss
  client/store/actions/session.js
  client/store/selectors/groups.js
  client/store/selectors/rats.js
  client/store/selectors/session.js
  client/store/selectors/users.js
  docs/selectors.md
  package.json
Labels: :skull_and_crossbones: Urgent, :zap: Enhancement

#207 [WEB-260][WEB-261][WEB-262][WEB-263] Fix Various problems intorduced in v2.9.0 (whoops)
  CHANGELOG.md
  client/components/UserDecalPanel.js
  client/pages/authorize.js
  client/pages/register.js
  client/store/initialState.js
  client/store/reducers/decals.js
  client/store/reducers/index.js
  client/store/reducers/session.js
  client/store/selectors/decals.js
  client/store/selectors/index.js
  package.json
Labels: :bug: Bugfix, :skull_and_crossbones: Urgent

#208 v2.9.1 - Fix things I borked
  CHANGELOG.md
  client/components/UserDecalPanel.js
  client/pages/authorize.js
  client/pages/register.js
  client/store/initialState.js
  client/store/reducers/decals.js
  client/store/reducers/index.js
  client/store/reducers/session.js
  client/store/selectors/decals.js
  client/store/selectors/index.js
  package.json
Labels: :package: Release, :skull_and_crossbones: Urgent
