Repository FuelRats/fuelrats.com, pull requests merged in 2019-06, with the labels that each got.

#148 Rescue list/search page.
  .babelrc
  client/components/AppLayout.js
  client/components/NProgress.js
  client/components/RatCard.js
  client/components/RescuesTablePanel.js
  client/components/TabbedPanel.js
  client/components/storefront/CartUpdateDialog.js
  client/helpers/faIconLibrary.js
  client/helpers/formatTime.js
  client/helpers/userHasPermission.js
  client/pages/admin/rescues.js
  client/pages/admin/rescues/list.js
  client/pages/paperwork/edit.js
  client/pages/paperwork/view.js
  client/routes.js
  client/scss/_pages.scss
  client/scss/colors/_playstation.scss
  client/scss/colors/_xbox.scss
  client/scss/components/_tabbed-panel.scss
  client/scss/components/_user-rats-tab.scss
  client/scss/core/_dialog.scss
  client/scss/pages/_paperwork.scss
  client/scss/pages/_rescue-search.scss
  client/store/actionTypes.js
  client/store/actions/rescues.js
  client/store/initialState.js
  client/store/reducers/authentication.js
  client/store/reducers/blogs.js
  client/store/reducers/epics.js
  client/store/reducers/groups.js
  client/store/reducers/index.js
  client/store/reducers/pageViews.js
  client/store/reducers/rats.js
  client/store/reducers/rescues.js
  client/store/reducers/rescuesByRat.js
  client/store/reducers/rescuesBySystem.js
  client/store/reducers/rescuesOverTime.js
  client/store/reducers/ships.js
  client/store/reducers/user.js
  client/store/reducers/wordpress.js
  client/store/selectors/index.js
  client/store/selectors/pageViews.js
  client/store/selectors/rats.js
  client/store/selectors/ships.js
  package.json
  yarn.lock
Labels: :bug: Bugfix, :sparkles: Feature, :zap: Enhancement

#153 fix(tabbed-panel-scss) Fixed profile tabs scroll
  client/scss/components/_tabbed-panel.scss
Labels: :bug: Bugfix

#152 feat/WEB-206/Added quotes table
  client/pages/paperwork/edit.js
Labels: :zap: Enhancement

#154 [WEB-217] Carousel image loader worker
  .eslintrc.js
  client/components/Carousel.js
  client/pages/index.js
  client/workers/image-loader.worker.js
  next.config.js
  package.json
  server/middlewares/csp.js
  yarn.lock
Labels: :skull_and_crossbones: Urgent, :zap: Enhancement

#156 Rescue count for rat cards
  client/components/CardControls.js
  client/components/RatCard.js
  client/helpers/formatTime.js
  client/scss/_components.scss
  client/scss/components/_card-controls.scss
  client/scss/components/_rat-panel.scss
  client/scss/pages/_rescue-search.scss
Labels: :zap: Enhancement

#157 Fix hidden pages
  client/scss/components/_page.scss
Labels: :bug: Bugfix

#162 Merge v2.7.1 hotfix into develop
  client/scss/components/_user-nicknames.scss
Labels: :bug: Bugfix, :zap: Enhancement

#163 [WEB-89] [WEB-207] Add achievement badges, (hopefully) fix some iOS scrolling problems
  client/components/Leaderboard/CodeRedIcon.js
  client/components/Leaderboard/FirstYearIcon.js
  client/components/Leaderboard/RescueAchievementIcon.js
  client/components/RatLeaderboardTable.js
  client/components/RescuesByRatTable.js
  client/components/svg/CodeRedSvg.js
  client/components/svg/DispatchSvg.js
  client/components/svg/FirstYearSvg.js
  client/components/svg/Rescue1000Svg.js
  client/components/svg/Rescue100Svg.js
  client/components/svg/Rescue200Svg.js
  client/components/svg/Rescue300Svg.js
  client/components/svg/Rescue400Svg.js
  client/components/svg/Rescue500Svg.js
  client/components/svg/Svg.js
  client/pages/leaderboard.js
  client/scss/_colors.scss
  client/scss/_components.scss
  client/scss/_core.scss
  client/scss/_lib.scss
  client/scss/colors/_blue.scss
  client/scss/colors/_gold.scss
  client/scss/components/_rat-leaderboard-table.scss
  client/scss/components/_rescues-by-rat-table.scss
  client/scss/core/_button.scss
  client/scss/core/_input.scss
  client/scss/core/_svg.scss
  client/scss/lib/_react-table.scss
Labels: :zap: Enhancement

#165 [WEB-207] fix page size.. cuz 20 is way too smol
  client/components/RatLeaderboardTable.js
Labels: :zap: Enhancement

#167 Clean up stuff around regex stuff
  client/components/AddNicknameForm.js
  client/data/RegExpr.js
  client/helpers/isUUID.js
  client/helpers/isUUIDv4.js
  client/pages/password-reset.js
  client/pages/register.js
  package.json
Labels: :bug: Bugfix, :zap: Enhancement

#169 [WEB-220] fix page SSR
  client/components/AppLayout.js
  client/components/AppLayout/PageLayout.js
  client/components/Carousel.js
  client/components/PageWrapper.js
  client/pages/_error.js
  client/pages/index.js
  client/pages/version.js
  client/scss/_override.scss
  client/scss/app.scss
  client/scss/override/_dark-mode.scss
  package.json
  yarn.lock
Labels: :bug: Bugfix, :zap: Enhancement

#170 [WEB-221] global image worker & blob url storage
  client/components/AppLayout/PageLayout.js
  client/components/Carousel.js
  client/pages/index.js
  client/services/imageLoader.js
  client/store/actionTypes.js
  client/store/actions/images.js
  client/store/actions/index.js
  client/store/initialState.js
  client/store/reducers/flags.js
  client/store/reducers/images.js
  client/store/reducers/index.js
  client/store/selectors/images.js
  client/store/selectors/index.js
  client/workers/image-loader.worker.js
Labels: :sparkles: Feature, :zap: Enhancement

#168 [WEB-211] Account profile redesign
  client/components/AddNicknameForm.js
  client/components/ProfileHeader.js
  client/components/UserDecalPanel.js
  client/components/UserDetailsPanel.js
  client/components/UserNicknamesPanel.js
  client/components/UserOverview.js
  client/helpers/formatTime.js
  client/pages/profile.js
  client/scss/_components.scss
  client/scss/components/_avatar.scss
  client/scss/components/_profile-header.scss
  client/scss/components/_user-decals-table.scss
  client/scss/components/_user-details.scss
  client/scss/components/_user-nicknames.scss
Labels: :zap: Enhancement

#172 [WEB-211] Fixes to profile
  client/components/UserNicknamesPanel.js
  client/scss/components/_user-overview-tab.scss
Labels: :bug: Bugfix

#173 Fix/add nick password
  client/components/AddNicknameForm.js
Labels: :bug: Bugfix, :skull_and_crossbones: Urgent

#174 2.7.3 - Fix nickname password input
  client/components/AddNicknameForm.js
Labels: :package: Release, :skull_and_crossbones: Urgent
