Repository FuelRats/fuelrats.com, pull requests merged in 2020-01, with the labels that each got.

#211 Fix wp-content proxy
  server/middlewares/proxy.js
Labels: :bug: Bugfix

#212 fix donation radio option shuffling
  client/scss/components/_donate-form.scss
Labels: :bug: Bugfix

#213 v2.9.2 [WEB-267] fix session initialization to handle post-registration.
  .nvmrc
  CHANGELOG.md
  client/store/actions/session.js
Labels: :bug: Bugfix, :package: Release, :skull_and_crossbones: Urgent

#215 Rework some paperwork stuff (and 1 other left over from another job)
  .eslintignore
  .gitignore
  .stylelintignore
  .vscode/settings.json
  .vscode/tasks.json
  CHANGELOG.md
  CONTRIBUTING.md
  client/components/AppLayout/AppLayout.js
  client/components/AppLayout/PageTransitionContainer.js
  client/components/AppLayout/PageWrapper.js
  client/components/AppLayout/index.js
  client/components/AppLayout/withStripe.js
  client/components/Carousel.js
  client/components/DonateForm.js
  client/components/Modal/Modal.js
  client/components/Modal/index.js
  client/components/RadioInput/index.js
  client/components/RatCard/index.js
  client/components/UserMenu/index.js
  client/pages/blog/author/[author]/index.js
  client/pages/blog/author/[author]/page/[page].js
  client/pages/blog/category/[category]/index.js
  client/pages/blog/category/[category]/page/[page].js
  client/pages/blog/page/[page].js
  client/pages/i-need-fuel.js
  client/pages/paperwork/[rescueId]/edit.js
  client/pages/paperwork/[rescueId]/index.js
  client/pages/paperwork/[rescueId]/view.js
  client/pages/version/raw.js
  client/routes.js
  client/services/imageLoader.js
  client/store/selectors/groups.js
  client/store/selectors/rescues.js
  client/store/selectors/users.js
  client/store/utility/chainReducers.js
  jsconfig.json
  next.config.js
  package.json
  typings/DefinePlugin.d.ts
  yarn.lock
Labels: :zap: Enhancement

#217 Hotfix/edit permission check bug
  client/store/selectors/rats.js
  client/store/selectors/rescues.js
Labels: :bug: Bugfix, :skull_and_crossbones: Urgent

#218 Hotfix/donation captcha
  .env.template
  CHANGELOG.md
  client/components/DonateForm.js
  client/scss/components/_donate-form.scss
  next.config.js
  package.json
  server/environment.js
  server/router/stripeApi.js
  yarn.lock
Labels: :bug: Bugfix, :package: Release, :skull_and_crossbones: Urgent
