Repository FuelRats/fuelrats.com, pull requests merged in 2020-04, with the labels that each got.

#228 [WEB-277] simplify applayout... A LOT
  .eslintrc.js
  CHANGELOG.md
  next.config.js
  package.json
  postcss.config.js
  public/sitemap.xml
  src/components/AppLayout/AppLayout.js
  src/components/AppLayout/AuthenticatedPage.js
  src/components/AppLayout/PageTransitionContainer.js
  src/components/AppLayout/PageWrapper.js
  src/components/AppLayout/index.js
  src/components/LoginModal.js
  src/components/NProgress.js
  src/components/UserMenu/NavItem.js
  src/components/UserMenu/UserMenu.js
  src/helpers/gIPTools.js
  src/pages/[slug].js
  src/pages/_app.js
  src/pages/_error.js
  src/pages/about.js
  src/pages/acknowledgements.js
  src/pages/admin/rescues/index.js
  src/pages/authorize.js
  src/pages/blog/[blogId].js
  src/pages/blog/index.js
  src/pages/donate/[result].js
  src/pages/donate/index.js
  src/pages/epic/nominate.js
  src/pages/forgot-password.js
  src/pages/i-need-fuel.js
  src/pages/index.js
  src/pages/leaderboard.js
  src/pages/paperwork/[rescueId]/edit.js
  src/pages/paperwork/[rescueId]/index.js
  src/pages/password-reset.js
  src/pages/profile/[tab].js
  src/pages/register.js
  src/pages/version/index.js
  src/routes.js
  src/store/actionTypes.js
  src/store/actions/session.js
  src/store/initialState.js
  src/store/reducers/session.js
  src/store/selectors/session.js
  yarn.lock
Labels: :sparkles: Feature, :zap: Enhancement

#191 [WEB-235] refactoring password reset (resubmit)
  src/pages/verify.js
  src/routes.js
  src/store/actionTypes.js
  src/store/actions/index.js
  src/store/actions/verify.js
Labels: :zap: Enhancement

#230 Donation API IP Blocking.
  CHANGELOG.md
  docs/using_stripe_bans.md
  package.json
  src/components/ChangePasswordModal.js
  src/components/DonateForm.js
  src/components/LoginModal.js
  src/pages/epic/nominate.js
  src/pages/forgot-password.js
  src/pages/paperwork/[rescueId]/edit.js
  src/scss/_pages.scss
  src/scss/components/_store-error.scss
  src/scss/core/_dialog.scss
  src/scss/pages/_donate.scss
  src/scss/pages/_store-cart.scss
  src/server/environment.mjs
  src/server/middlewares/csp.mjs
  src/server/router/index.mjs
  src/server/router/stripeApi/TrafficControl.mjs
  src/server/router/stripeApi/authorization.mjs
  src/server/router/stripeApi/document.mjs
  src/server/router/stripeApi/error.mjs
  src/server/router/stripeApi/index.mjs
  src/server/server.mjs
  yarn.lock
Labels: :electric_plug: Dependencies, :sparkles: Feature, :zap: Enhancement

#233 Fix stuff I broke
  .env.template
  CHANGELOG.md
  package.json
  src/pages/_app.js
  src/server/router/stripeApi/authorization.mjs
  src/server/router/stripeApi/index.mjs
  src/store/actions/session.js
Labels: :bug: Bugfix, :skull_and_crossbones: Urgent

#234 v2.11.1
  .env.template
  CHANGELOG.md
  package.json
  src/pages/_app.js
  src/server/router/stripeApi/authorization.mjs
  src/server/router/stripeApi/index.mjs
  src/store/actions/session.js
Labels: :package: Release, :skull_and_crossbones: Urgent

#236 Fix redirect on login
  CHANGELOG.md
  package.json
  src/store/actions/authentication.js
Labels: :bug: Bugfix, :skull_and_crossbones: Urgent

#237 v2.11.2
  CHANGELOG.md
  package.json
  src/store/actions/authentication.js
Labels: :package: Release

#238 [WEB-234] APIv3 request data handling
  src/components/AddRatForm.js
  src/components/ChangePasswordModal.js
  src/components/RatCard/RatCard.js
  src/components/UserDecalPanel.js
  src/helpers/presenters.js
  src/pages/paperwork/[rescueId]/edit.js
  src/server/middlewares/proxy.mjs
  src/store/actions/authentication.js
  src/store/actions/decals.js
  src/store/actions/epics.js
  src/store/actions/leaderboard.js
  src/store/actions/rats.js
  src/store/actions/rescues.js
  src/store/actions/ships.js
  src/store/actions/user.js
  src/store/reducers/decals.js
Labels: :gear: Task

#239 Merge what we have on APIv3 Migration.
  src/pages/verify.js
  src/routes.js
  src/store/actionTypes.js
  src/store/actions/index.js
  src/store/actions/verify.js
Labels: :zap: Enhancement

#220 [WEB-162] Disable Profile Modal
  CHANGELOG.md
  src/components/DisableProfileModal.js
  src/components/ProfileHeader.js
  src/scss/core/_dialog.scss
  src/store/actionTypes.js
Labels: :sparkles: Feature
