Repository FuelRats/fuelrats.com, pull requests merged in 2020-12, with the labels that each got.

#298 Sort cases with "last created to first created" on initial load.
  CHANGELOG.md
  src/store/actions/rescues.js
Labels: :bug: Bugfix

#302 Developer panel
  CHANGELOG.md
  next.config.js
  src/components/DeveloperPanel/ClientSubmitMessageBox.js
  src/components/DeveloperPanel/DeveloperPanel.js
  src/components/DeveloperPanel/index.js
  src/components/Forms/OAuthClientForm.js
  src/components/MessageBox/MessageBox.js
  src/components/MessageBox/MessageBox.module.scss
  src/components/TabbedPanel.js
  src/components/UserRatsPanel.js
  src/pages/profile/[tab].js
  src/scss/core/_code.scss
  src/store/actionTypes.js
  src/store/actions/clients.js
  src/store/initialState.js
  src/store/reducers/frAPIResources.js
  src/store/selectors/clients.js
  src/store/selectors/users.js
Labels: :sparkles: Feature

#303 WEB-295: Added closing button to RescueDetailsCont
  CHANGELOG.md
  src/components/RescueDetails/RescueDetails.module.scss
  src/components/RescueDetails/RescueDetailsContent.js
Labels: :zap: Enhancement
