Repository FuelRats/fuelrats.com, pull requests merged in 2020-07, with the labels that each got.

#253 Add default checkbox styling
  src/scss/core/_input.scss
Labels: :sparkles: Feature

#255 [WEB-233] APIv3 Leaderboard
  package.json
  src/components/RatLeaderboardTable.js
  src/scss/_components.scss
  src/scss/_lib.scss
  src/scss/components/_react-tables.scss
  src/scss/core/_button.scss
  src/scss/core/_input.scss
  src/scss/lib/_react-table.scss
  src/store/actions/leaderboard.js
  src/store/initialState.js
  src/store/reducers/index.js
  src/store/reducers/leaderboard.js
  src/store/selectors/leaderboard.js
  yarn.lock
Labels: :zap: Enhancement

#259 fix(register-page): default TOS and Privacy acceptance to false
  src/pages/register.js
Labels: :bug: Bugfix, :package: Release, :skull_and_crossbones: Urgent

#261 Fix redux middleware
  package.json
  src/store/actions/session.js
  src/store/index.js
  yarn.lock
Labels: :bug: Bugfix, :zap: Enhancement

#262 Fix babel transform issue, also drop support for IE11
  .babelrc
  CHANGELOG.md
  package.json
  src/server/environment.mjs
  src/server/middlewares/ua-redirect.mjs
  src/server/server.mjs
  yarn.lock
Labels: :bug: Bugfix

#264 Fix the leaderboard (some more)
  src/components/RatLeaderboardTable.js
Labels: :bug: Bugfix

#265 [WEB-288] Fix <DisableProfileModal />
  package.json
  src/components/DisableProfileModal.js
  yarn.lock
Labels: :bug: Bugfix

#266 Fix issues with Registration page
  src/components/Forms/RegistrationForm/RegistrationErrorBox.js
  src/pages/register.js
  src/scss/components/_page-content.scss
  src/store/actions/authentication.js
Labels: :bug: Bugfix
