Repository FuelRats/fuelrats.com, pull requests merged in 2021-09, with the labels that each got.

#370 JSON Doc Editor / Locale file editor
  .eslintrc.js
  CHANGELOG.md
  src/components/JsonEditor/JsonEditor.js
  src/components/JsonEditor/JsonEditor.module.scss
  src/components/JsonEditor/JsonField.js
  src/components/JsonEditor/JsonObject.js
  src/components/JsonEditor/index.js
  src/data/apiErrorLocalisations.js
  src/pages/api/qms/locales/[id].js
  src/pages/api/qms/locales/index.js
  src/pages/api/qms/queue.js
  src/pages/locale-editor.js
  src/scss/_fonts.scss
  src/scss/_helpers.scss
  src/scss/helpers/_motion.scss
  src/scss/pages/locale-editor.module.scss
  src/util/server/errors.js
  src/util/server/middleware/jsonApiRoute/JsonApiContext.js
Labels: Type | Feature :sparkles:, Type | Enhancement :zap:

#372 Fix/carousel loading weirdness
  .babelrc.js
  package.json
  src/components/Carousel.js
  src/components/TagsInput.js
  src/pages/index.js
  yarn.lock
Labels: Type | Bug :bug:, Type | Dependencies :electric_plug:

#373 Disallow rescues to be edited while they are open
  CHANGELOG.md
  src/store/selectors/rescues.js
Labels: Type | Enhancement :zap:

#375 #355 fix Avatar uploader jank
  .config/headers.config.js
  CHANGELOG.md
  src/components/MessageBox/MessageBox.js
  src/components/MessageBox/MessageBox.module.scss
  src/components/ProfileHeader/ProfileHeader.js
  src/components/ProfileUserAvatar/ProfileUserAvatar.js
  src/components/ProfileUserAvatar/ProfileUserAvatar.module.scss
  src/components/Slider/Slider.js
  src/components/Slider/index.js
  src/components/Switch/Switch.module.scss
  src/components/UploadAvatarModal/UploadAvatarMessageBox.js
  src/components/UploadAvatarModal/UploadAvatarModal.js
  src/components/UploadAvatarModal/UploadAvatarModal.module.scss
  src/components/UserDecalPanel/UserDecalPanel.module.scss
  src/components/UserMenu/UserMenu.js
  src/scss/_components.scss
  src/scss/_lib.scss
  src/scss/components/_avatar.scss
  src/scss/components/_file-dropzone.scss
  src/scss/lib/_rc-slider.scss
  src/scss/lib/_react-easy-crop.scss
  src/store/selectors/clients.js
  src/store/selectors/decals.js
  src/store/selectors/groups.js
  src/store/selectors/nicknames.js
  src/store/selectors/statistics.js
  src/store/selectors/users.js
  src/util/fontawesome/library.js
Labels: Type | Bug :bug:, Type | Enhancement :zap:

#377 🐛: Updated styling for currently selected checkbox
  src/scss/core/_input.scss
Labels: Type | Bug :bug:
